apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: my-awesome-service-secret-store
  namespace: my-awesome-service-ns
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: my-awesome-service-sa
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: my-awesome-service-rds-pg-password-secret
  namespace: my-awesome-service-ns
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: my-awesome-service-secret-store
    kind: SecretStore
  target:
    name: my-awesome-service-rds-pg-password-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres_password
      remoteRef:
        key: arn:aws:secretsmanager:eu-west-1:902409284726:secret:my-awesome-service-db-name-1-rds-password-flztcqxm-8rGFL2
        property: # empty - this is a plain-text secret and not a key-value pair
