version: '2'

networks:
  lemp_net:

services:
  nginx:
    image: nginx:1
    container_name: lemp_container_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/code
      - .docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - lemp_net

  mariadb:
    image: mariadb:10
    container_name: lemp_container_mariadb
    volumes:
      - .docker/mariadb/db_persistence:/var/lib/mysql:rw
      - .docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - nginx
    networks:
      - lemp_net

  mysql:
    image: mysql:8
    container_name: lemp_container_mysql
    volumes:
      - .docker/mysql/db_persistence:/var/lib/mysql:rw
      - .docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - nginx
    networks:
      - lemp_net

  php-fpm:
    build:
      dockerfile: .docker/php-fpm/Dockerfile
      context: .
    container_name: lemp_container_php_fpm
    volumes:
      - ./src:/code
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_HOST: mariadb
    networks:
      - lemp_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: lemp_container_phpMyAdmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_ARBITRARY: 0
      PMA_HOSTS: mysql,mariadb
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mariadb
      - mysql
    networks:
      - lemp_net

  composer:
    image: prooph/composer:7.4 # remember that this version needs to match the php-fpm image-version!
    container_name: lemp_container_composer
    restart: 'no'
    command: "install"
    volumes:
      - ./src:/app
    networks:
      - lemp_net




