name: PHP Linting

on: [ push, pull_request ]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: overtrue/phplint@8.1
        with:
          path: .
          options: --exclude=vendor
